python measure_shift_accuracies.py --model_file_name resnet18_v7_normalized_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name resnet18_pretrained_v7_normalized_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name resnet18_antialiased_v7_normalized_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name resnet18_v7_truly_shift_invariant_normalized_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name train_v7_transformer_2_final.pt --batch_size 25
python measure_shift_accuracies.py --model_file_name train_v7_transformer_2_deit.pt --batch_size 25
python measure_shift_accuracies.py --model_file_name train_v7_transformer_2_deit_distilled.pt --batch_size 25
python measure_shift_accuracies.py --model_file_name resnet18_v7_40_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name resnet18_pretrained_v7_40_normalized_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name resnet18_antialiased_v7_40_normalized_final.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name resnet18_v7_40_truly_shift_invariant_normalized.pt --batch_size 50
python measure_shift_accuracies.py --model_file_name train_v7_transformer_40_2.pt --batch_size 25
python measure_shift_accuracies.py --model_file_name train_v7_transformer_40_2_deit.pt --batch_size 25
python measure_shift_accuracies.py --model_file_name train_v7_transformer_40_2_deit_distilled.pt --batch_size 25
