# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_v7_normalized_final.pt --normalize
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_pretrained_v7_normalized_final.pt --normalize
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_antialiased_v7_normalized_final.pt --normalize
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_v7_truly_shift_invariant_normalized_final.pt --normalize --batch_size 75
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name train_v7_transformer_2_final.pt --normalize --batch_size 25
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name train_v7_transformer_2_deit.pt --normalize --batch_size 25
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name train_v7_transformer_2_deit_distilled.pt --normalize --batch_size 25
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name resnet18_v7_normalized_final.pt --normalize
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name resnet18_pretrained_v7_normalized_final.pt --normalize
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name resnet18_antialiased_v7_normalized_final.pt --normalize
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name resnet18_v7_truly_shift_invariant_normalized_final.pt --normalize  --batch_size 75
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name train_v7_transformer_2_final.pt --normalize --batch_size 25
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name train_v7_transformer_2_deit.pt --normalize --batch_size 25
# CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet --model_file_name train_v7_transformer_2_deit_distilled.pt --normalize --batch_size 25
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_v7_40_final.pt --normalize
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_pretrained_v7_40_normalized_final.pt --normalize
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_antialiased_v7_40_normalized_final.pt --normalize
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name resnet18_v7_40_truly_shift_invariant_normalized.pt --normalize --batch_size 75
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name train_v7_transformer_40_2.pt --normalize --batch_size 25
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name train_v7_transformer_40_2_deit.pt --normalize --batch_size 25
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_unseen_10 --model_file_name train_v7_transformer_40_2_deit_distilled.pt --normalize --batch_size 25
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name resnet18_v7_40_final.pt --normalize
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name resnet18_pretrained_v7_40_normalized_final.pt --normalize
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name resnet18_antialiased_v7_40_normalized_final.pt --normalize
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name resnet18_v7_40_truly_shift_invariant_normalized.pt --normalize  --batch_size 75
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name train_v7_transformer_40_2.pt --normalize --batch_size 25
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name train_v7_transformer_40_2_deit.pt --normalize --batch_size 25
CUDA_VISIBLE_DEVICES=4 python measure_accuracy.py --dataset_name image_train_v7_shapenet_40 --model_file_name train_v7_transformer_40_2_deit_distilled.pt --normalize --batch_size 25